name: Build and deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Create 404 page
              run: |
                  printf -- "---\npermalink: /404.html\n---\n" > 404.md
                  printf -- "> **Note:** You accessed a link that returned a 404. Copy the link address and add it into Vendetta.\n\n" >> 404.md

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  enable_jekyll: true
                  exclude_assets: '.git,.github'